### ISSUE TITLE
Too lazy to make a pull or a fork

### ISSUE THREAD

**Issue by dmonteroh** [Qwynn/EWVGMM#1]
I made a change to "Furniture_Production" in ThingsDef_Buildings, added charcoal production to FueledStove:

`              <recipes>
			<li>CookMealSimple</li>
			<li>CookMealFine</li>
			<li>CookMealLavish</li>
			<li>MakePemmican</li>
			<li>MakeCharcoal</li>
		</recipes>`

I'll just post my findings here, ludeon forum pms are weird.

**Comment by dmonteroh** [comment]
A good way to avoid that would be to rewrite the Make Charcoal recipe from MM and give it a ```

`<recipeUsers>
	  <li>FueledStove</li>
	  <li>ElectricStove</li>
	</recipeUsers>`

**Comment by dmonteroh** [comment]
An error that exists from MM is that the fueled smithy can't spin wire, as far as I remember the anvil isn't working at the moment, so the only way to make wire is with the electric smithy.
Rewriting the Spin Wire recipe and adding a <recipeUsers> would be a good solution.

Something like this: http://pastebin.com/EUAKB1Lv
(actual names for forges are ElectricSmelter and Forge)

**Comment by Qwynn** [comment]
I'll add them in, thanks!

**Comment by dmonteroh** [comment]
Yeah, I think the production buildings won't need to be written a lot of times, instead I think it's easier to have the receipts worked out.

You should look into FMOverrides, instead of writing the whole def new, you can just add in the new text or replace old values without worrying about the rest of the info. It's what I use to balance seedsplease, works really well.

**Comment by Qwynn** [comment]
I've been eyeing MFO but haven't worked with it much yet. I think my first project with it will be a rewrite of the balance patch I use for my mod collection before I move it on to other projects.

Let me know if you find anything else that needs fixing!

**Comment by dmonteroh** [comment]
Will do, I'm working my way with a tribal start in order to test out everything as I go.

**Comment by dmonteroh** [comment]
![image](https://cloud.githubusercontent.com/assets/16642619/23131547/275e2a8e-f769-11e6-825c-8799e5baf2e1.png)
I think this is more related to normal EW, but still

**Comment by Qwynn** [comment]
That's Fluffy's Colony Manager right? Is it actually producing meat or is it just a description issue? If it's just a description issue, do vanilla stone blocks do the same thing? I assume it's because I'm hooking the recipe into the butchery script (like stone blocks).
